### ISSUE TITLE
Dead code in build.nu

### ISSUE THREAD

**Issue by matklad** [DeterminateSystems/nuenv#2]
First time reading nu code, so I might be asking a dumb question here, but isn’t this whole if a no-op?

https://github.com/DeterminateSystems/nuenv/blob/bf5a203980baff4c2bda2344339deb9fecc149ab/nuenv/builder.nu#L69

It seems that it prints stuff, but doesn’t actually add it to PATH?

**Comment by lucperkins** [comment]
@matklad That's actually intended to be a no-op and solely for logging purposes. The full set of packages that will be added to the `PATH` is determined [here](https://github.com/DeterminateSystems/nuenv/blob/bf5a203980baff4c2bda2344339deb9fecc149ab/nuenv/builder.nu#L34-L38) while the `PATH` is set [here](https://github.com/DeterminateSystems/nuenv/blob/bf5a203980baff4c2bda2344339deb9fecc149ab/nuenv/builder.nu#L83-L88).

**Comment by lucperkins** [comment]
@matklad I did make a few inline docs changes that will hopefully make that more clear!
